const pokemon = [
    { id: 1, name: "Bulbasaur", types: ["grass", "poison"], entry: "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon." },
    { id: 2, name: "Ivysaur", types: ["grass", "poison"], entry: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs." },
    { id: 3, name: "Venusaur", types: ["grass", "poison"], entry: "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight." },
    { id: 4, name: "Charmander", types: ["fire"], entry: "It has a preference for hot places. When it rains, steam is said to spout from the tip of its tail." },
    { id: 5, name: "Charmeleon", types: ["fire"], entry: "It lashes about with its tail to knock down its foe. The tail burns with a blue flame." },
    { id: 6, name: "Charizard", types: ["fire", "flying"], entry: "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally." },
    { id: 7, name: "Squirtle", types: ["water"], entry: "After birth, its back swells and hardens into a shell. Powerfully sprays water from its mouth." },
    { id: 8, name: "Wartortle", types: ["water"], entry: "Often hides in water to stalk unwary prey. Its tail is large and covered with fluffy fur." },
    { id: 9, name: "Blastoise", types: ["water"], entry: "It crushes its foe under its heavy body. Its powerful cannons fire water jets capable of punching holes through steel." },
    { id: 10, name: "Caterpie", types: ["bug"], entry: "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls." },
    { id: 11, name: "Metapod", types: ["bug"], entry: "A steel-hard shell protects its tender body. It quietly endures hardships while awaiting evolution." },
    { id: 12, name: "Butterfree", types: ["bug", "flying"], entry: "In battle, it flaps its wings at high speed to release highly toxic dust into the air." },
    { id: 13, name: "Weedle", types: ["bug", "poison"], entry: "Often found in forests, eating leaves. It has a sharp venomous stinger on its head." },
    { id: 14, name: "Kakuna", types: ["bug", "poison"], entry: "Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators." },
    { id: 15, name: "Beedrill", types: ["bug", "poison"], entry: "It has three poisonous stingers on its forelegs and tail. They are used to jab its enemy repeatedly." },
    { id: 16, name: "Pidgey", types: ["normal", "flying"], entry: "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand." },
    { id: 17, name: "Pidgeotto", types: ["normal", "flying"], entry: "Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder." },
    { id: 18, name: "Pidgeot", types: ["normal", "flying"], entry: "When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp." },
    { id: 19, name: "Rattata", types: ["normal"], entry: "Bites anything when it attacks. Small and very quick, it is a common sight in many places." },
    { id: 20, name: "Raticate", types: ["normal"], entry: "It uses its whiskers to maintain its balance. It gnaws on anything with its tough fangs." },
    { id: 21, name: "Spearow", types: ["normal", "flying"], entry: "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne." },
    { id: 22, name: "Fearow", types: ["normal", "flying"], entry: "With its huge and magnificent wings, it can keep aloft without ever having to land for rest." },
    { id: 23, name: "Ekans", types: ["poison"], entry: "Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole." },
    { id: 24, name: "Arbok", types: ["poison"], entry: "It is rumored that the ferocious warning markings on its belly differ from area to area." },
    { id: 25, name: "Pikachu", types: ["electric"], entry: "When several of these Pokémon gather, their electricity could build and cause lightning storms." },
    { id: 26, name: "Raichu", types: ["electric"], entry: "Its long tail serves as a ground to protect itself from its own high-voltage power." },
    { id: 27, name: "Sandshrew", types: ["ground"], entry: "Burrows deep underground in arid locations far from water. It only emerges to hunt for food." },
    { id: 28, name: "Sandslash", types: ["ground"], entry: "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape." },
    { id: 29, name: "Nidoran♀", types: ["poison"], entry: "Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns." },
    { id: 30, name: "Nidorina", types: ["poison"], entry: "The female's horn develops slowly. Prefers physical attacks such as clawing and biting." },
    { id: 31, name: "Nidoqueen", types: ["poison", "ground"], entry: "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves." },
    { id: 32, name: "Nidoran♂", types: ["poison"], entry: "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom." },
    { id: 33, name: "Nidorino", types: ["poison"], entry: "An aggressive Pokémon that is quick to attack. The horn on its head secretes a powerful venom." },
    { id: 34, name: "Nidoking", types: ["poison", "ground"], entry: "It uses its powerful tail in battle to smash, constrict, then break the prey's bones." },
    { id: 35, name: "Clefairy", types: ["fairy"], entry: "Its magical and cute appeal has many admirers. It is rare and found only in certain areas." },
    { id: 36, name: "Clefable", types: ["fairy"], entry: "A timid fairy Pokémon that is rarely seen. It will run and hide the moment it senses people." },
    { id: 37, name: "Vulpix", types: ["fire"], entry: "At the time of its birth, it has just one tail. The tail splits from its tip as it grows older." },
    { id: 38, name: "Ninetales", types: ["fire"], entry: "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse." },
    { id: 39, name: "Jigglypuff", types: ["normal", "fairy"], entry: "When its huge eyes light up, it sings a lullaby that puts everyone to sleep." },
    { id: 40, name: "Wigglytuff", types: ["normal", "fairy"], entry: "Its body is filled with air, so it can freely float by inhaling deeply." },
    { id: 41, name: "Zubat", types: ["poison", "flying"], entry: "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets." },
    { id: 42, name: "Golbat", types: ["poison", "flying"], entry: "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly." },
    { id: 43, name: "Oddish", types: ["grass", "poison"], entry: "During the daytime, it stays in the cold underground to avoid the sun. It grows by bathing in moonlight." },
    { id: 44, name: "Gloom", types: ["grass", "poison"], entry: "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey." },
    { id: 45, name: "Vileplume", types: ["grass", "poison"], entry: "The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up." },
    { id: 46, name: "Paras", types: ["bug", "grass"], entry: "Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host." },
    { id: 47, name: "Parasect", types: ["bug", "grass"], entry: "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places." },
    { id: 48, name: "Venonat", types: ["bug", "poison"], entry: "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night." },
    { id: 49, name: "Venomoth", types: ["bug", "poison"], entry: "The dust-like scales covering its wings are color-coded to indicate the kinds of poison it has." },
    { id: 50, name: "Diglett", types: ["ground"], entry: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground." },
    { id: 51, name: "Dugtrio", types: ["ground"], entry: "A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground." },
    { id: 52, name: "Meowth", types: ["normal"], entry: "Adores circular objects. Wanders the streets on a nightly basis to look for shiny coins." },
    { id: 53, name: "Persian", types: ["normal"], entry: "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness." },
    { id: 54, name: "Psyduck", types: ["water"], entry: "While lulling its enemies with vacant look, this wily Pokémon will use psychokinetic powers." },
    { id: 55, name: "Golduck", types: ["water"], entry: "Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa." },
    { id: 56, name: "Mankey", types: ["fighting"], entry: "Extremely quick to anger. It could be docile one moment then thrashing away the next instant." },
    { id: 57, name: "Primeape", types: ["fighting"], entry: "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught." },
    { id: 58, name: "Growlithe", types: ["fire"], entry: "Very protective of its territory. It will bark and bite to repel intruders from its space." },
    { id: 59, name: "Arcanine", types: ["fire"], entry: "A Pokémon that has been admired since the past for its beauty. It runs agilely as if on wings." },
    { id: 60, name: "Poliwag", types: ["water"], entry: "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand." },
    { id: 61, name: "Poliwhirl", types: ["water"], entry: "Capable of living in or out of water. When out of water, it sweats to keep its body slimy." },
    { id: 62, name: "Poliwrath", types: ["water", "fighting"], entry: "An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers." },
    { id: 63, name: "Abra", types: ["psychic"], entry: "Using its ability to sense danger, it teleports to safety before its enemies can attack." },
    { id: 64, name: "Kadabra", types: ["psychic"], entry: "It emits alpha waves from its body. It is said to have something to do with extrasensory powers." },
    { id: 65, name: "Alakazam", types: ["psychic"], entry: "Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5000." },
    { id: 66, name: "Machop", types: ["fighting"], entry: "Loves to build its muscles. It trains in all sorts of physical exercises to become stronger." },
    { id: 67, name: "Machoke", types: ["fighting"], entry: "Its muscular body is so powerful that it must wear a power-save belt to be able to regulate its motions." },
    { id: 68, name: "Machamp", types: ["fighting"], entry: "Using its four arms, it throws powerful punches that can send even the largest opponents flying." },
    { id: 69, name: "Bellsprout", types: ["grass", "poison"], entry: "A carnivorous Pokémon that traps and eats bugs. It uses its root feet to soak up needed moisture." },
    { id: 70, name: "Weepinbell", types: ["grass", "poison"], entry: "It spits out poisonpowder to immobilize the enemy and then finishes it with a spray of acid." },
    { id: 71, name: "Victreebel", types: ["grass", "poison"], entry: "Said to live in huge colonies deep in jungles, although no one has ever returned from there." },
    { id: 72, name: "Tentacool", types: ["water", "poison"], entry: "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid." },
    { id: 73, name: "Tentacruel", types: ["water", "poison"], entry: "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey." },
    { id: 74, name: "Geodude", types: ["rock", "ground"], entry: "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them." },
    { id: 75, name: "Graveler", types: ["rock", "ground"], entry: "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction." },
    { id: 76, name: "Golem", types: ["rock", "ground"], entry: "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage." },
    { id: 77, name: "Ponyta", types: ["fire"], entry: "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time." },
    { id: 78, name: "Rapidash", types: ["fire"], entry: "Very competitive, this Pokémon will chase anything that moves fast in the hopes of racing it." },
    { id: 79, name: "Slowpoke", types: ["water", "psychic"], entry: "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack." },
    { id: 80, name: "Slowbro", types: ["water", "psychic"], entry: "The Shellder that is latched onto Slowpoke's tail is said to feed on the host's left over scraps." },
    { id: 81, name: "Magnemite", types: ["electric", "steel"], entry: "Uses anti-gravity to stay suspended. Appears without warning and uses Thunder Wave and similar moves." },
    { id: 82, name: "Magneton", types: ["electric", "steel"], entry: "Formed by several Magnemite linked together. They frequently appear when sunspots flare up." },
    { id: 83, name: "Farfetch'd", types: ["normal", "flying"], entry: "The plant stalk it holds is its weapon. The stalk is used like a sword to cut all sorts of things." },
    { id: 84, name: "Doduo", types: ["normal", "flying"], entry: "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints." },
    { id: 85, name: "Dodrio", types: ["normal", "flying"], entry: "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake." },
    { id: 86, name: "Seel", types: ["water"], entry: "The protruding horn on its head is very hard. It is used for bashing through thick ice." },
    { id: 87, name: "Dewgong", types: ["water", "ice"], entry: "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters." },
    { id: 88, name: "Grimer", types: ["poison"], entry: "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories." },
    { id: 89, name: "Muk", types: ["poison"], entry: "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison." },
    { id: 90, name: "Shellder", types: ["water"], entry: "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open." },
    { id: 91, name: "Cloyster", types: ["water", "ice"], entry: "When attacked, it launches its horns in quick volleys. Its innards have never been seen." },
    { id: 92, name: "Gastly", types: ["ghost", "poison"], entry: "Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without warning." },
    { id: 93, name: "Haunter", types: ["ghost", "poison"], entry: "Because it loves to frighten people, it tries to lick anything that moves to scare them." },
    { id: 94, name: "Gengar", types: ["ghost", "poison"], entry: "Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright." },
    { id: 95, name: "Onix", types: ["rock", "ground"], entry: "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black." },
    { id: 96, name: "Drowzee", types: ["psychic"], entry: "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams." },
    { id: 97, name: "Hypno", types: ["psychic"], entry: "When it locks eyes with an enemy, it will use a mix of psi moves such as Hypnosis and Confusion." },
    { id: 98, name: "Krabby", types: ["water"], entry: "Its pincers are not only powerful weapons, they are used for balance when walking sideways." },
    { id: 99, name: "Kingler", types: ["water"], entry: "The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use." },
    { id: 100, name: "Voltorb", types: ["electric"], entry: "Usually found in power plants. Easily mistaken for a Poké Ball, they have zapped many people." },
    { id: 101, name: "Electrode", types: ["electric"], entry: "It stores electric energy under very high pressure. It often explodes with little or no provocation." },
    { id: 102, name: "Exeggcute", types: ["grass", "psychic"], entry: "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms." },
    { id: 103, name: "Exeggutor", types: ["grass", "psychic"], entry: "Legend has it that on rare occasions, one of its heads will drop off and continue on as an Exeggcute." },
    { id: 104, name: "Cubone", types: ["ground"], entry: "Wears the skull of its deceased mother. It cries at night, which echoes in lonely places." },
    { id: 105, name: "Marowak", types: ["ground"], entry: "The bone it carries is extremely powerful. It can smash through rock and hard objects with ease." },
    { id: 106, name: "Hitmonlee", types: ["fighting"], entry: "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides." },
    { id: 107, name: "Hitmonchan", types: ["fighting"], entry: "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see." },
    { id: 108, name: "Lickitung", types: ["normal"], entry: "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies." },
    { id: 109, name: "Koffing", types: ["poison"], entry: "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning." },
    { id: 110, name: "Weezing", types: ["poison"], entry: "Where two kinds of poison gases meet, 2 Koffings can fuse into a Weezing over many years." },
    { id: 111, name: "Rhyhorn", types: ["ground", "rock"], entry: "Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying." },
    { id: 112, name: "Rhydon", types: ["ground", "rock"], entry: "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees." },
    { id: 113, name: "Chansey", types: ["normal"], entry: "A rare and elusive Pokémon that is said to bring happiness to those who manage to get it." },
    { id: 114, name: "Tangela", types: ["grass"], entry: "The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks." },
    { id: 115, name: "Kangaskhan", types: ["normal"], entry: "The infant rarely ventures out of its mother's protective pouch until it is 3 years old." },
    { id: 116, name: "Horsea", types: ["water"], entry: "Known to shoot down flying bugs with precision blasts of ink from the surface of the water." },
    { id: 117, name: "Seadra", types: ["water"], entry: "Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail." },
    { id: 118, name: "Goldeen", types: ["water"], entry: "Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen." },
    { id: 119, name: "Seaking", types: ["water"], entry: "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks." },
    { id: 120, name: "Staryu", types: ["water"], entry: "An enigmatic Pokémon that can effortlessly regenerate any appendage it loses in battle." },
    { id: 121, name: "Starmie", types: ["water", "psychic"], entry: "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem." },
    { id: 122, name: "Mr. Mime", types: ["psychic", "fairy"], entry: "If interrupted while it is miming, it will slap around the offender with its broad hands." },
    { id: 123, name: "Scyther", types: ["bug", "flying"], entry: "With ninja-like agility and speed, it can create the illusion that there is more than one." },
    { id: 124, name: "Jynx", types: ["ice", "psychic"], entry: "It seductively wiggles its hips as it walks. It can cause people to dance in unison with it." },
    { id: 125, name: "Electabuzz", types: ["electric"], entry: "Normally found near power plants, they can wander away and cause major blackouts in cities." },
    { id: 126, name: "Magmar", types: ["fire"], entry: "Its body always burns with an orange glow that enables it to hide perfectly among flames." },
    { id: 127, name: "Pinsir", types: ["bug"], entry: "If it fails to crush the victim in its pincers, it will swing it around and toss it hard." },
    { id: 128, name: "Tauros", types: ["normal"], entry: "When it targets an enemy, it charges furiously while whipping its body with its long tails." },
    { id: 129, name: "Magikarp", types: ["water"], entry: "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today." },
    { id: 130, name: "Gyarados", types: ["water", "flying"], entry: "Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage." },
    { id: 131, name: "Lapras", types: ["water", "ice"], entry: "A Pokémon that has been overhunted almost to extinction. It can ferry people across the water." },
    { id: 132, name: "Ditto", types: ["normal"], entry: "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy." },
    { id: 133, name: "Eevee", types: ["normal"], entry: "Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones." },
    { id: 134, name: "Vaporeon", types: ["water"], entry: "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's." },
    { id: 135, name: "Jolteon", types: ["electric"], entry: "It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts." },
    { id: 136, name: "Flareon", types: ["fire"], entry: "When storing thermal energy in its body, its temperature could soar to over 1600 degrees." },
    { id: 137, name: "Porygon", types: ["normal"], entry: "A Pokémon that consists entirely of programming code. Capable of moving freely in cyberspace." },
    { id: 138, name: "Omanyte", types: ["rock", "water"], entry: "Although long extinct, in rare cases, it can be genetically resurrected from fossils." },
    { id: 139, name: "Omastar", types: ["rock", "water"], entry: "A prehistoric Pokémon that died out when its heavy shell made it impossible to catch prey." },
    { id: 140, name: "Kabuto", types: ["rock", "water"], entry: "A Pokémon that was resurrected from a fossil found in what was once the ocean floor eons ago." },
    { id: 141, name: "Kabutops", types: ["rock", "water"], entry: "Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids." },
    { id: 142, name: "Aerodactyl", types: ["rock", "flying"], entry: "A ferocious, prehistoric Pokémon that goes for the enemy's throat with its serrated saw-like fangs." },
    { id: 143, name: "Snorlax", types: ["normal"], entry: "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful." },
    { id: 144, name: "Articuno", types: ["ice", "flying"], entry: "A legendary bird Pokémon that is said to appear to doomed people who are lost in icy mountains." },
    { id: 145, name: "Zapdos", types: ["electric", "flying"], entry: "A legendary bird Pokémon that is said to appear from clouds while dropping enormous lightning bolts." },
    { id: 146, name: "Moltres", types: ["fire", "flying"], entry: "Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames." },
    { id: 147, name: "Dratini", types: ["dragon"], entry: "Long considered a mythical Pokémon until recently when a small colony was found living underwater." },
    { id: 148, name: "Dragonair", types: ["dragon"], entry: "A mystical Pokémon that exudes a gentle aura. Has the ability to change climate conditions." },
    { id: 149, name: "Dragonite", types: ["dragon", "flying"], entry: "An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans." },
    { id: 150, name: "Mewtwo", types: ["psychic"], entry: "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments." },
    { id: 151, name: "Mew", types: ["psychic"], entry: "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide." },
    { id: 152, name: "Chikorita", types: ["grass"], entry: "A sweet aroma gently wafts from the leaf on its head. It is docile and loves to soak up the sun's rays." },
    { id: 153, name: "Bayleef", types: ["grass"], entry: "The scent of spices comes from around its neck. Somehow, sniffing it makes you want to fight." },
    { id: 154, name: "Meganium", types: ["grass"], entry: "The fragrance of its flower soothes and calms emotions. In battle, it gives off more of its becalming scent." },
    { id: 155, name: "Cyndaquil", types: ["fire"], entry: "It is timid, and always curls itself up in a ball. If attacked, it flares up its back for protection." },
    { id: 156, name: "Quilava", types: ["fire"], entry: "This Pokémon is fully covered by nonflammable fur. It can withstand any kind of fire attack." },
    { id: 157, name: "Typhlosion", types: ["fire"], entry: "If its rage peaks, it becomes so hot that anything that touches it will instantly go up in flames." },
    { id: 158, name: "Totodile", types: ["water"], entry: "Despite the smallness of its body, its jaws are very powerful. Its bite can crush even hard berries." },
    { id: 159, name: "Croconaw", types: ["water"], entry: "If it loses a fang, a new one grows back in its place. There are always 48 fangs lining its mouth." },
    { id: 160, name: "Feraligatr", types: ["water"], entry: "When it bites with its massive and powerful jaws, it shakes its head and savagely tears its victim up." },
    { id: 161, name: "Sentret", types: ["normal"], entry: "When acting as a lookout, it warns others of danger by screeching and hitting the ground with its tail." },
    { id: 162, name: "Furret", types: ["normal"], entry: "It makes a nest to suit its long and skinny body. The nest is impossible for other Pokémon to enter." },
    { id: 163, name: "Hoothoot", types: ["normal", "flying"], entry: "It always stands on one foot. It changes feet so fast, the movement can rarely be seen." },
    { id: 164, name: "Noctowl", types: ["normal", "flying"], entry: "Its eyes are specially developed to enable it to see clearly even in murky darkness and minimal light." },
    { id: 165, name: "Ledyba", types: ["bug", "flying"], entry: "It is very timid. It will be afraid to move if it is alone. But it will be active if it is in a group." },
    { id: 166, name: "Ledian", types: ["bug", "flying"], entry: "When the stars flicker in the night sky, it flutters about, scattering a glowing powder." },
    { id: 167, name: "Spinarak", types: ["bug", "poison"], entry: "It lies still in the same pose for days in its web, waiting for its unsuspecting prey to wander close." },
    { id: 168, name: "Ariados", types: ["bug", "poison"], entry: "It spins string not only from its rear but also from its mouth. It is hard to tell which end is which." },
    { id: 169, name: "Crobat", types: ["poison", "flying"], entry: "The development of wings on its legs enables it to fly fast but also makes it tough to stop and rest." },
    { id: 170, name: "Chinchou", types: ["water", "electric"], entry: "It shoots positive and negative electricity between the tips of its two antennae and zaps its enemies." },
    { id: 171, name: "Lanturn", types: ["water", "electric"], entry: "The light it emits is so bright that it can illuminate the sea's surface from a depth of over three miles." },
    { id: 172, name: "Pichu", types: ["electric"], entry: "It is not yet skilled at storing electricity. It may send out a jolt if amused or startled." },
    { id: 173, name: "Cleffa", types: ["fairy"], entry: "Many appear when the night skies are filled with shooting stars. They disappear with sunrise." },
    { id: 174, name: "Igglybuff", types: ["normal", "fairy"], entry: "It has a very soft body. If it starts to roll, it will bounce all over and be impossible to stop." },
    { id: 175, name: "Togepi", types: ["fairy"], entry: "The shell seems to be filled with joy. It is said that it will share good luck when treated kindly." },
    { id: 176, name: "Togetic", types: ["fairy", "flying"], entry: "They say that it will appear before kindhearted, caring people and shower them with happiness." },
    { id: 177, name: "Natu", types: ["psychic", "flying"], entry: "Because its wings aren't yet fully grown, it has to hop to get around. It is always staring at something." },
    { id: 178, name: "Xatu", types: ["psychic", "flying"], entry: "They say that it stays still and quiet because it is seeing both the past and future at the same time." },
    { id: 179, name: "Mareep", types: ["electric"], entry: "Its fleece grows continually. In the summer, the fleece is fully shed, but it grows back in a week." },
    { id: 180, name: "Flaaffy", types: ["electric"], entry: "As a result of storing too much electricity, it developed patches where even downy wool won't grow." },
    { id: 181, name: "Ampharos", types: ["electric"], entry: "The tail's tip shines brightly and can be seen from far away. It acts as a beacon for lost people." },
    { id: 182, name: "Bellossom", types: ["grass"], entry: "Plump and friendly, it has a lovely way of dancing that attracts attention. The petals on its head shrink." },
    { id: 183, name: "Marill", types: ["water", "fairy"], entry: "The tip of its tail is filled with oil that is lighter than water, so it acts as a flotation device." },
    { id: 184, name: "Azumarill", types: ["water", "fairy"], entry: "By keeping still and listening intently, it can tell what is in even wild, fast-moving rivers." },
    { id: 185, name: "Sudowoodo", types: ["rock"], entry: "Although it always pretends to be a tree, its composition appears more similar to rock than to vegetation." },
    { id: 186, name: "Politoed", types: ["water"], entry: "The curled hair on its head proves its status as a king. It is said that the longer the curl, the more it is respected." },
    { id: 187, name: "Hoppip", types: ["grass", "flying"], entry: "To keep from being blown away by the wind, they gather in clusters. They do enjoy gentle breezes, though." },
    { id: 188, name: "Skiploom", types: ["grass", "flying"], entry: "The bloom on top of its head opens and closes as the temperature fluctuates up and down." },
    { id: 189, name: "Jumpluff", types: ["grass", "flying"], entry: "Once it catches the wind, it deftly controls its cotton-puff spores to float, even around the world." },
    { id: 190, name: "Aipom", types: ["normal"], entry: "Its tail is so powerful that it can use it to grab a tree branch and hold itself up in the air." },
    { id: 191, name: "Sunkern", types: ["grass"], entry: "It may drop out of the sky suddenly. If attacked by a Spearow, it will violently shake its leaves." },
    { id: 192, name: "Sunflora", types: ["grass"], entry: "It converts sunlight into energy. In the darkness after sunset, it closes its petals and becomes still." },
    { id: 193, name: "Yanma", types: ["bug", "flying"], entry: "If it flaps its wings really fast, it can generate shock waves that will shatter windows in the area." },
    { id: 194, name: "Wooper", types: ["water", "ground"], entry: "This Pokémon lives in cold water. It will leave the water to search for food when it gets cold outside." },
    { id: 195, name: "Quagsire", types: ["water", "ground"], entry: "This carefree Pokémon has an easy-going nature. While swimming, it always bumps into boat hulls." },
    { id: 196, name: "Espeon", types: ["psychic"], entry: "It uses the fine hair that covers its body to sense air currents and predict its enemy's actions." },
    { id: 197, name: "Umbreon", types: ["dark"], entry: "When agitated, this Pokémon protects itself by spraying poisonous sweat from its pores." },
    { id: 198, name: "Murkrow", types: ["dark", "flying"], entry: "Feared and loathed by many, it is believed to bring misfortune to all those who see it at night." },
    { id: 199, name: "Slowking", types: ["water", "psychic"], entry: "It has incredible intellect and intuition. Whatever the situation, it remains calm and collected." },
    { id: 200, name: "Misdreavus", types: ["ghost"], entry: "It likes to bite at people's heads from behind. It thrives by absorbing the horror and fear of its victims." },
    { id: 201, name: "Unown", types: ["psychic"], entry: "Their shapes look like hieroglyphs on ancient tablets. It is said that the two are somehow related." },
    { id: 202, name: "Wobbuffet", types: ["psychic"], entry: "It hates light and shock. If attacked, it inflates its body to pump up its counterstrike." },
    { id: 203, name: "Girafarig", types: ["normal", "psychic"], entry: "Its tail has a small brain of its own. Beware! If you get close, it may react to your scent and bite." },
    { id: 204, name: "Pineco", types: ["bug"], entry: "It likes to make its shell thicker by adding layers of tree bark. The additional weight doesn't bother it." },
    { id: 205, name: "Forretress", types: ["bug", "steel"], entry: "Its entire body is shielded by a steel-hard shell. What lurks inside the armor is a total mystery." },
    { id: 206, name: "Dunsparce", types: ["normal"], entry: "When spotted, this Pokémon escapes backward by furiously boring into the ground with its tail." },
    { id: 207, name: "Gligar", types: ["ground", "flying"], entry: "It flies straight at its target's face then clamps down on the startled victim to inject poison." },
    { id: 208, name: "Steelix", types: ["steel", "ground"], entry: "Its body has been compressed deep under the ground. As a result, it is even harder than a diamond." },
    { id: 209, name: "Snubbull", types: ["fairy"], entry: "Although it looks frightening, it is actually kind and affectionate. It is very popular among women." },
    { id: 210, name: "Granbull", types: ["fairy"], entry: "It is actually timid and easily spooked. If attacked, it flails about to fend off its attacker." },
    { id: 211, name: "Qwilfish", types: ["water", "poison"], entry: "To fire its poison spikes, it must inflate its body by drinking over 2.6 gallons of water all at once." },
    { id: 212, name: "Scizor", types: ["bug", "steel"], entry: "It has a hard body that can withstand even bullets. Its pincers pack a powerful punch that can crush foes." },
    { id: 213, name: "Shuckle", types: ["bug", "rock"], entry: "The berries it stores in its vase-like shell decompose and become a gooey liquid." },
    { id: 214, name: "Heracross", types: ["bug", "fighting"], entry: "This powerful Pokémon thrusts its prized horn under its enemy's bellies then lifts and throws them." },
    { id: 215, name: "Sneasel", types: ["dark", "ice"], entry: "Its paws conceal sharp claws. If attacked, it suddenly extends the claws and startles its enemy." },
    { id: 216, name: "Teddiursa", types: ["normal"], entry: "If it finds honey, its crescent mark glows. It always licks its paws because they are soaked with honey." },
    { id: 217, name: "Ursaring", types: ["normal"], entry: "Although it is a good climber, it prefers to snap trees with its forelegs and eat fallen berries." },
    { id: 218, name: "Slugma", types: ["fire"], entry: "It never sleeps. It has to keep moving because if it stopped, its magma body would cool and harden." },
    { id: 219, name: "Magcargo", types: ["fire", "rock"], entry: "The shell on its back is just skin that has cooled and hardened. It breaks easily with a slight touch." },
    { id: 220, name: "Swinub", types: ["ice", "ground"], entry: "It rubs its snout on the ground to find and dig up food. It sometimes discovers hot springs." },
    { id: 221, name: "Piloswine", types: ["ice", "ground"], entry: "Because the long hair all over its body obscures its sight, it just keeps charging repeatedly." },
    { id: 222, name: "Corsola", types: ["water", "rock"], entry: "In a south sea nation, the people live in communities that are built on groups of these Pokémon." },
    { id: 223, name: "Remoraid", types: ["water"], entry: "It has superb accuracy. The water it shoots out can strike even moving prey from more than 300 feet." },
    { id: 224, name: "Octillery", types: ["water"], entry: "It traps enemies with its suction-cupped tentacles then smashes them with its rock-hard head." },
    { id: 225, name: "Delibird", types: ["ice", "flying"], entry: "It carries food all day long. There are tales about lost people who were saved by the food it had." },
    { id: 226, name: "Mantine", types: ["water", "flying"], entry: "As it majestically swims, it doesn't care if Remoraid attach to it for scavenging its leftovers." },
    { id: 227, name: "Skarmory", types: ["steel", "flying"], entry: "Its sturdy wings look heavy, but they are actually hollow and light, allowing it to fly freely in the sky." },
    { id: 228, name: "Houndour", types: ["dark", "fire"], entry: "It uses different kinds of cries for communicating with others of its kind and for pursuing its prey." },
    { id: 229, name: "Houndoom", types: ["dark", "fire"], entry: "If you are burned by the flames it shoots from its mouth, the pain will never go away." },
    { id: 230, name: "Kingdra", types: ["water", "dragon"], entry: "It is said that it usually hides in underwater caves. It can create whirlpools by yawning." },
    { id: 231, name: "Phanpy", types: ["ground"], entry: "It swings its long snout around playfully, but because it is so strong, that can be dangerous." },
    { id: 232, name: "Donphan", types: ["ground"], entry: "It has sharp, hard tusks and a rugged hide. Its Tackle is strong enough to knock down a house." },
    { id: 233, name: "Porygon2", types: ["normal"], entry: "This upgraded version of Porygon is designed for space exploration. It can't fly, though." },
    { id: 234, name: "Stantler", types: ["normal"], entry: "Those who stare at its antlers will gradually become unable to control their limbs and movements." },
    { id: 235, name: "Smeargle", types: ["normal"], entry: "A special fluid oozes from the tip of its tail. It paints the fluid everywhere to mark its territory." },
    { id: 236, name: "Tyrogue", types: ["fighting"], entry: "It is always bursting with energy. To make itself stronger, it keeps on fighting even if it loses." },
    { id: 237, name: "Hitmontop", types: ["fighting"], entry: "If you become enchanted by its smooth, elegant, dance-like kicks, you may get drilled hard." },
    { id: 238, name: "Smoochum", types: ["ice", "psychic"], entry: "Its lips are the most sensitive parts on its body. It always uses its lips first to examine things." },
    { id: 239, name: "Elekid", types: ["electric"], entry: "It rotates its arms to generate electricity, but it tires easily, so it charges up only a little bit." },
    { id: 240, name: "Magby", types: ["fire"], entry: "Each and every time it inhales and exhales, hot embers dribble out of its mouth and nostrils." },
    { id: 241, name: "Miltank", types: ["normal"], entry: "Its milk is packed with nutrition, making it the ultimate beverage for the sick or weary." },
    { id: 242, name: "Blissey", types: ["normal"], entry: "Anyone who takes even one bite of Blissey's egg becomes unfailingly caring and pleasant to everyone." },
    { id: 243, name: "Raikou", types: ["electric"], entry: "The rain clouds it carries let it fire thunderbolts at will. They say that it descended with lightning." },
    { id: 244, name: "Entei", types: ["fire"], entry: "Volcanoes erupt when it barks. Unable to contain its sheer power, it races headlong around the land." },
    { id: 245, name: "Suicune", types: ["water"], entry: "Said to be the reincarnation of north winds, it can instantly purify filthy, murky water." },
    { id: 246, name: "Larvitar", types: ["rock", "ground"], entry: "It feeds on soil. After it has eaten a large mountain, it will fall asleep so it can grow." },
    { id: 247, name: "Pupitar", types: ["rock", "ground"], entry: "Its shell is as hard as sheet rock, and it is also very strong. Its thrashing can topple a mountain." },
    { id: 248, name: "Tyranitar", types: ["rock", "dark"], entry: "Its body can't be harmed by any sort of attack, so it is very eager to make challenges against enemies." },
    { id: 249, name: "Lugia", types: ["psychic", "flying"], entry: "It is said to be the guardian of the seas. It is rumored to have been seen on the night of a storm." },
    { id: 250, name: "Ho-Oh", types: ["fire", "flying"], entry: "Legends claim this Pokémon flies the world's skies continuously on its magnificent seven-colored wings." },
    { id: 251, name: "Celebi", types: ["psychic", "grass"], entry: "This Pokémon wanders across time. Grass and trees flourish in the forests in which it has appeared." },
    { id: 252, name: "Treecko", types: ["grass"], entry: "The soles of its feet have tiny spikes that enable it to walk on walls and ceilings." },
    { id: 253, name: "Grovyle", types: ["grass"], entry: "The leaves growing out of its body are convenient for camouflaging it in a forest." },
    { id: 254, name: "Sceptile", types: ["grass"], entry: "The leaves on its arms can slice down thick trees. It is without peer in jungle combat." },
    { id: 255, name: "Torchic", types: ["fire"], entry: "A fire burns inside, so it feels very warm to hug. It launches fireballs of 1,800 degrees Fahrenheit." },
    { id: 256, name: "Combusken", types: ["fire", "fighting"], entry: "It lashes out with 10 kicks per second. Its strong fighting instinct compels it to keep fighting." },
    { id: 257, name: "Blaziken", types: ["fire", "fighting"], entry: "In battle, it blows out intense flames from its wrists and attacks foes courageously." },
    { id: 258, name: "Mudkip", types: ["water"], entry: "The fin on its head acts as highly sensitive radar. Using this fin, it can sense the movements of water and air." },
    { id: 259, name: "Marshtomp", types: ["water", "ground"], entry: "The surface of its body is enveloped by a thin, sticky film that enables it to live on land." },
    { id: 260, name: "Swampert", types: ["water", "ground"], entry: "Its arms are rock-hard. With one swing, it can batter down its foe. It makes its nest on beautiful beaches." },
    { id: 261, name: "Poochyena", types: ["dark"], entry: "At first sight, it takes a bite at anything that moves. This Pokémon chases after prey until the victim becomes exhausted." },
    { id: 262, name: "Mightyena", types: ["dark"], entry: "It will always obey the commands of a skilled trainer. Its behavior arises from its living in packs in ancient times." },
    { id: 263, name: "Zigzagoon", types: ["normal"], entry: "Rubbing its nose against the ground, it always wanders about back and forth in search of something." },
    { id: 264, name: "Linoone", types: ["normal"], entry: "When running in a straight line, it can top 60 miles per hour. However, it has a tough time with curved roads." },
    { id: 265, name: "Wurmple", types: ["bug"], entry: "It loves to eat leaves. If it is attacked by a Starly, it will defend itself with its spiked rear." },
    { id: 266, name: "Silcoon", types: ["bug"], entry: "It prepares for evolution using the energy it stored while it was a Wurmple. It keeps watch over its surroundings." },
    { id: 267, name: "Beautifly", types: ["bug", "flying"], entry: "Its colorfully patterned wings are its most prominent feature. It flies through flower-covered fields in search of pollen." },
    { id: 268, name: "Cascoon", types: ["bug"], entry: "To avoid detection by enemies, it hides motionlessly beneath large leaves and in the gaps of branches." },
    { id: 269, name: "Dustox", types: ["bug", "poison"], entry: "It is a nocturnal Pokémon that flies from fields and mountains to the attraction of streetlights at night." },
    { id: 270, name: "Lotad", types: ["water", "grass"], entry: "It looks like an aquatic plant and serves as a ferry to Pokémon that can't swim." },
    { id: 271, name: "Lombre", types: ["water", "grass"], entry: "It has a mischievous spirit. If it spots an angler, it will tug on the fishing line to interfere." },
    { id: 272, name: "Ludicolo", types: ["water", "grass"], entry: "Upon hearing an upbeat and cheerful rhythm, the cells in its body become very energetic and active." },
    { id: 273, name: "Seedot", types: ["grass"], entry: "It hangs off branches and absorbs nutrients. When it finishes eating, its body becomes so heavy that it drops to the ground." },
    { id: 274, name: "Nuzleaf", types: ["grass", "dark"], entry: "They live in holes bored in large trees. The sound of the grass flute they play scares people." },
    { id: 275, name: "Shiftry", types: ["grass", "dark"], entry: "By whipping up a gale with its three fans, it can make giant trees bend and crack like twigs." },
    { id: 276, name: "Taillow", types: ["normal", "flying"], entry: "It dislikes cold seasons. They migrate to other lands in search of warmth, flying over 180 miles a day." },
    { id: 277, name: "Swellow", types: ["normal", "flying"], entry: "It circles the sky in search of prey. When it spots one, it dives steeply to catch the prey." },
    { id: 278, name: "Wingull", types: ["water", "flying"], entry: "It makes its nest on a sheer cliff at the edge of the sea. It has trouble keeping its wings flapping in flight." },
    { id: 279, name: "Pelipper", types: ["water", "flying"], entry: "It skims the tops of waves as it flies. When it spots prey, it uses its large beak to scoop up the target." },
    { id: 280, name: "Ralts", types: ["psychic", "fairy"], entry: "It is highly attuned to the emotions of people and Pokémon. It hides if it senses hostility." },
    { id: 281, name: "Kirlia", types: ["psychic", "fairy"], entry: "It is said that a Kirlia that is exposed to the positive emotions of its trainer grows beautiful." },
    { id: 282, name: "Gardevoir", types: ["psychic", "fairy"], entry: "It has the power to predict the future. Its power peaks when it is protecting its trainer." },
    { id: 283, name: "Surskit", types: ["bug", "water"], entry: "From the tips of its feet, it secretes an oil that enables it to walk on water as if it were skating." },
    { id: 284, name: "Masquerain", types: ["bug", "flying"], entry: "Its antennae have eye patterns on them. Its four wings enable it to hover and fly in any direction." },
    { id: 285, name: "Shroomish", types: ["grass"], entry: "It spouts poison spores from the top of its head. These spores cause pain all over if inhaled." },
    { id: 286, name: "Breloom", types: ["grass", "fighting"], entry: "Its short arms stretch when it throws punches. Its technique is equal to that of pro boxers." },
    { id: 287, name: "Slakoth", types: ["normal"], entry: "It sleeps for 20 hours every day. Making drowsy those that see it is one of its abilities." },
    { id: 288, name: "Vigoroth", types: ["normal"], entry: "It can't keep still because its blood boils with energy. It runs through the fields and mountains all day." },
    { id: 289, name: "Slaking", types: ["normal"], entry: "Wherever it chooses to nest becomes its territory. It will savagely attack anything that intrudes." },
    { id: 290, name: "Nincada", types: ["bug", "ground"], entry: "Because it lived almost entirely underground, it is nearly blind. It uses its antennae instead." },
    { id: 291, name: "Ninjask", types: ["bug", "flying"], entry: "Because it moves so quickly, it sometimes becomes unseeable. It congregates around tree sap." },
    { id: 292, name: "Shedinja", types: ["bug", "ghost"], entry: "A strange Pokémon that appears to be a hollow shell. Its hard body doesn't move, not even a twitch." },
    { id: 293, name: "Whismur", types: ["normal"], entry: "Usually, its cries are like quiet murmurs. If frightened, it shrieks at the same volume as a jet plane." },
    { id: 294, name: "Loudred", types: ["normal"], entry: "The shock waves from its cries can tip over trucks. It stamps its feet to power up." },
    { id: 295, name: "Exploud", types: ["normal"], entry: "Its howls can be heard over six miles away. It emits all sorts of noises from the ports on its body." },
    { id: 296, name: "Makuhita", types: ["fighting"], entry: "It practices facing off with Makuhita for strength, but it can't even beat a Poliwrath yet." },
    { id: 297, name: "Hariyama", types: ["fighting"], entry: "It has the habit of challenging others without hesitation to tests of strength. It's been known to stand on train tracks." },
    { id: 298, name: "Azurill", types: ["normal", "fairy"], entry: "Its tail bounces like a rubber ball. It flings that tail around to fight opponents bigger than itself." },
    { id: 299, name: "Nosepass", types: ["rock"], entry: "Its nose is a magnet. As a result, this Pokémon always keeps its face pointing north." },
    { id: 300, name: "Skitty", types: ["normal"], entry: "It is fascinated by round objects. It can't stop playing with them until it tires and falls asleep." }
]



const grid = document.getElementById("pokemonGrid");
const search = document.getElementById("search");

const modal = document.getElementById("pokemonModal");
const modalImg = document.getElementById("modalImg");
const modalName = document.getElementById("modalName");
const modalId = document.getElementById("modalId");
const modalTypes = document.getElementById("modalTypes");
const closeModal = document.getElementById("closeModal");

const modalEntry = document.getElementById("modalEntry");



function render(list) {
    grid.innerHTML = "";
    list.forEach(p => {
        const card = document.createElement("div");
        card.className = "pokemon-card";

        card.innerHTML = `
            <img class="pokemon-img"
                src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${p.id}.png">
            <div class="pokemon-name">${p.name}</div>
            <div class="pokemon-types">
                ${p.types.map(t => `<span class="pokemon-type ${t}">${t}</span>`).join("")}
            </div>
        `;

        card.addEventListener("click", () => openModal(p));
        grid.appendChild(card);
    });
}

function openModal(pokemon) {
    modalImg.src = `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokemon.id}.png`;
    modalName.textContent = pokemon.name;
    modalId.textContent = `#${pokemon.id.toString().padStart(3, "0")}`;

    modalTypes.innerHTML = pokemon.types
        .map(t => `<span class="pokemon-type ${t}">${t}</span>`)
        .join("");

    modalEntry.textContent = pokemon.entry; // <-- Make sure this line is included

    modal.classList.remove("hidden");
}


closeModal.addEventListener("click", () => {
    modal.classList.add("hidden");
});

modal.addEventListener("click", e => {
    if (e.target === modal) {
        modal.classList.add("hidden");
    }
});


search.addEventListener("input", e => {
    const value = e.target.value.toLowerCase();
    render(pokemon.filter(p => p.name.toLowerCase().includes(value)));
});

render(pokemon);
